galaxy_info:
  author: Adam Mack
  description: Save configurations for network devices
  company: Red Hat
  license: "license (BSD, MIT)"
  min_ansible_version: 2.7
  galaxy_tags:
    - network
    - arista
    - nexus
    - ios
    - asa
    - cisco
