---
- name: "Include ACL Tasks"
  include_tasks: "{{ ansible_network_os }}.yml"
  when: ansible_network_os is defined
  with_first_found:
    - files:
        - "tasks/{{ ansible_network_os }}.yml"
      skip: true
