vlans:
  - name: Dev_Network
    vlan_id: 10
  - name: Prod_Network
    vlan_id: 20

interface_config:
  - name: Ethernet1/1
    enabled: True

  - name: Ethernet1/2
    enabled: False

  - name: Ethernet1/3
    enabled: False

  - name: Ethernet1/4
    enabled: False

  - name: Ethernet1/5
    enabled: False

  - name: Ethernet1/6
    description: vPC PeerLink
    enabled: True

  - name: Ethernet1/7
    description: vPC PeerLink
    enabled: True

  - name: port-channel10
    description: Palo Alto Dev Network
    enabled: True
    portchannel_id: 10
    trunk:
      allowed_vlans:
        - "10"
    vpc: 10
    members:
      - member: Ethernet1/1
        mode: active

  - name: port-channel100
    description: vPC PeerLink
    enabled: True
    portchannel_id: 100
    vpc_peerlink: True
    members:
      - member: Ethernet1/6
        mode: active
      - member: Ethernet1/7
        mode: active
